+Create database ItlaBuildings
CREATE TABLE USER_(
ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE  AS ('USR'+right('00'+CONVERT(varchar,ID),(2))),
NAMES VARCHAR(20),
LASTNAME VARCHAR(20),
BIRTHDATE DATE,
USER_TYPE VARCHAR(10),
USER_ VARCHAR(20),
PASSWORD_ VARCHAR(20)
)

CREATE TABLE CAREER(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CAREER VARCHAR(40)
)

INSERT INTO CAREER VALUES
('simulaciones interactivas y videojuegos'),
('telecomunicaciones'),
('inteligencia artificial'),
('informática forense'),
('redes de información'),
('mecatrónica'),
('manufactura automatizada'),
('multimedia'),
('seguridad informática'),
('desarrollo de software'),
('analítica y ciencia de los datos')
SELECT * FROM CAREER


CREATE TABLE VISIT (
ID_VISIT int IDENTITY(1,1) NOT NULL PRIMARY KEY,
CODE  AS ('VIS'+right('00'+CONVERT(varchar,ID_VISIT),(2))),
NAME_VISIT VARCHAR(20),
LASTNAME VARCHAR(20),
ID_CAREER INT NOT NULL,
MAIL VARCHAR(20),
ID_BUILDING INT NOT NULL,
ID_SECTION INT NOT NULL,
CHECKIN DATETIME,
CHECKOUT DATETIME,
REASON VARCHAR(100),
CONSTRAINT FK_BUILDING_VISIT FOREIGN KEY (ID_BUILDING) REFERENCES BUILDING(ID),
CONSTRAINT FK_CAREER_VISIT FOREIGN KEY (ID_CAREER) REFERENCES CAREER(ID),
CONSTRAINT FK_BUILDING_SECTION FOREIGN KEY (ID_SECTION) REFERENCES SECTION(ID)
) 
SELECT * FROM VISIT
INSERT INTO VISIT VALUES
('Jorge','Samuel',2,'jorge@itla.edu.do',1,3,'2022-08-19 01:34:17','2022-08-19 03:00:50','Clases presenciales')

CREATE TABLE BUILDING(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
BUILDING VARCHAR(20),
)
INSERT INTO BUILDING VALUES
('EDIFICIO 1'),
('EDIFICIO 2'),
('EDIFICIO 3'),
('EDIFICIO 4'),
('BIBLIOTECA'),
('RESIDENCIA ACADEMICA')
SELECT * FROM BUILDING


CREATE TABLE SECTION(
ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
SECTION VARCHAR(10)
)
INSERT INTO SECTION VALUES
('1A1'),
('1B1'),
('1C1'),
('1D1'),
('1E2'),
('1F2'),
('1G2'),
('1H2'),
('1I3'),
('1J3'),
('1K3'),
('1L3'),

('2A1'),
('2B1'),
('2C1'),
('2D1'),
('2E2'),
('2F2'),
('2G2'),
('2H2'),
('2I3'),
('2J3'),
('2K3'),
('2L3'),

('3A1'),
('3B1'),
('3C1'),
('3D1'),
('3E2'),
('3F2'),
('3G2'),
('3H2'),
('3I3'),
('3J3'),
('3K3'),
('3L3'),

('4A1'),
('4B1'),
('4C1'),
('4D1'),
('4E2'),
('4F2'),
('4G2'),
('4H2'),
('4I3'),
('4J3'),
('4K3'),
('4L3')
SELECT * FROM SECTION


---------------------------------------//VIEW---------------------------------------

CREATE VIEW VW_VISITAS AS
SELECT V.ID_VISIT AS 'Id visita',V.CODE,V.NAME_VISIT AS 'Nombre',V.LASTNAME AS 'Apellido',V.ID_CAREER AS 'Id carrera',C.CAREER AS 'Carrera',V.MAIL AS 'Correo', V.ID_BUILDING AS 'Id edificio',B.BUILDING AS 'Edificio',V.ID_SECTION AS 'Id Aula',S.SECTION AS 'Aula',V.CHECKIN AS 'Hora de llegada',V.CHECKOUT AS 'Hora de salida',V.REASON AS 'Motivo de visita'  from VISIT V 
INNER JOIN SECTION S ON V.ID_SECTION = S.ID
INNER JOIN BUILDING B ON V.ID_BUILDING = B.ID
INNER JOIN CAREER C ON V.ID_CAREER = C.ID

---------------------------------------//STORED PROCEDURES--------------------------

------insert user---------
GO
CREATE PROC SP_INSERT_USER
@NAMES VARCHAR(20),
@LASTNAME VARCHAR(20),
@BIRTHDATE DATE,
@USER_TYPE VARCHAR(10),
@USER_ VARCHAR(20),
@PASSWORD_ VARCHAR(20)
AS
INSERT INTO USER_ VALUES(@NAMES,@LASTNAME,@BIRTHDATE,@USER_TYPE,@USER_, @PASSWORD_)

--------LOGIN USER---------------
GO
CREATE PROC SP_LOGIN_USER_
@USER_ VARCHAR(20),
@PASSWORD_ VARCHAR(20)
AS
SELECT * FROM USER_ WHERE USER_ = @USER_ AND PASSWORD_ = @PASSWORD_  

--------SELECT ALL VISITS----------
GO
CREATE PROC SP_SELECT_VISIT AS
SELECT * FROM VW_VISITAS
--------INSERT VISIT----------
GO
CREATE PROC SP_INSERT_VISIT 
@NAME_VISIT NVARCHAR(20),
@LASTNAME NVARCHAR(20),
@ID_CAREER INT ,
@MAIL NVARCHAR(20),
@ID_BUILDING INT ,
@ID_SECTION INT,
@CHECKIN DATETIME,
@CHECKOUT DATETIME,
@REASON NVARCHAR(100)
AS
INSERT INTO VISIT VALUES(
@NAME_VISIT ,@LASTNAME , @ID_CAREER , @MAIL , @ID_BUILDING, @ID_SECTION , @CHECKIN , @CHECKOUT ,@REASON) 

--------EDIT VISIT----------
GO
CREATE PROC SP_EDIT_VISIT 
@ID_VISIT INT,
@NAME_VISIT NVARCHAR(20),
@LASTNAME NVARCHAR(20),
@ID_CAREER INT,
@MAIL NVARCHAR(20),
@ID_BUILDING INT ,
@ID_SECTION INT ,
@CHECKIN DATETIME,
@CHECKOUT DATETIME,
@REASON NVARCHAR(100)
AS
UPDATE VISIT SET
NAME_VISIT = @NAME_VISIT ,LASTNAME = @LASTNAME , ID_CAREER = @ID_CAREER ,MAIL =  @MAIL , ID_BUILDING = @ID_BUILDING,ID_SECTION = @ID_SECTION , CHECKIN = @CHECKIN ,CHECKOUT = @CHECKOUT ,REASON = @REASON WHERE 
ID_VISIT = @ID_VISIT

-----------FIND_VISIT---------
GO
CREATE PROC SP_FIND_VISIT 
@FIND NVARCHAR(30)
AS 
SELECT * FROM VISIT
WHERE NAME_VISIT LIKE @FIND + '%'


-----------DELETE VISIT-------
GO
CREATE PROC SP_DELETE_VISIT
@ID INT
AS
DELETE FROM VISIT
WHERE ID_VISIT = @ID

-----------LIST_USER---------
GO
CREATE PROC SP_LIST_USERS
AS
select * from USER_

-----------LIST BUILDINGS-----------
GO
CREATE PROC SP_LIST_BUILDING
AS 
SELECT (BUILDING) FROM BUILDING
-------------------------------------------------------------------------------------




